### ISSUE TITLE
Help me please!

### ISSUE THREAD

**Issue by MomboteQ** [MiguelRAvila/RelaxedDotfiles#1]
Hello, will you help or tell me how to install it? Because I don't know much about linux and i3 gaps.

**Comment by migueravila** [comment]
Hey! @MombotTv 

Sorry for the late answer but I haven't been on this repo for a while. Well there isn't just a way to install all the config files because each one are for different tools/apps/programs. It depends on each one and how they use it. I totally recommend you to start looking for an i3 setup guide and then go for other programs like Polybar, terminal commands, and so.
